base_url = "https://demonkingswarn.is-a.dev/website-beta"
title = "DemonKingSwarn's Webpage"

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
